// <auto-generated />
using System;
using GroceryTracker.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryTracker.Core.Migrations
{
    [DbContext(typeof(GroceryTrackerDbContext))]
    partial class GroceryTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GroceryTracker.Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsBuiltIn = true,
                            Name = "Produce",
                            NormalizedName = "produce",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsBuiltIn = true,
                            Name = "Dairy",
                            NormalizedName = "dairy",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            IsBuiltIn = true,
                            Name = "Meat & Seafood",
                            NormalizedName = "meat & seafood",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            IsBuiltIn = true,
                            Name = "Bakery",
                            NormalizedName = "bakery",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            IsBuiltIn = true,
                            Name = "Pantry",
                            NormalizedName = "pantry",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            IsBuiltIn = true,
                            Name = "Frozen",
                            NormalizedName = "frozen",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            IsBuiltIn = true,
                            Name = "Beverages",
                            NormalizedName = "beverages",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            IsBuiltIn = true,
                            Name = "Household",
                            NormalizedName = "household",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            IsBuiltIn = true,
                            Name = "Other",
                            NormalizedName = "other",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.GroceryList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("ProfileId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreferredStoreId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListId");

                    b.HasIndex("PreferredStoreId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.ListStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("ListStores");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProfileId", "Date");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.TripItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TripId");

                    b.ToTable("TripItems");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.GroceryList", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Profile", "Profile")
                        .WithMany("Lists")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Item", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Category", "DefaultCategory")
                        .WithMany()
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroceryTracker.Core.Entities.Profile", "Profile")
                        .WithMany("Items")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultCategory");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.ListItem", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.GroceryList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.Store", "PreferredStore")
                        .WithMany()
                        .HasForeignKey("PreferredStoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Item");

                    b.Navigation("List");

                    b.Navigation("PreferredStore");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.ListStore", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.GroceryList", "List")
                        .WithMany("Stores")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Store", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Profile", "Profile")
                        .WithMany("Stores")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Trip", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Profile", "Profile")
                        .WithMany("Trips")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.TripItem", b =>
                {
                    b.HasOne("GroceryTracker.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryTracker.Core.Entities.Trip", "Trip")
                        .WithMany("Items")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.GroceryList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Profile", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Lists");

                    b.Navigation("Stores");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("GroceryTracker.Core.Entities.Trip", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
